version: "3.9"
services:
  apache:
    image: httpd:alpine3.16
    container_name: apache
    volumes:
      - ./public:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - 8082:80
    networks:
      - doc-net
  apache-php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: apache-php-fpm
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_connect_back=0 remote_enable=1 log=/tmp/xdebug.log"
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
    - ./public:/var/www/html
    networks:
      - doc-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
  apache-postgres:
    image: postgres:14.5-alpine3.16
    container_name: apache-postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456789
    networks:
      - doc-net
networks:
  doc-net:

volumes:
  postgresdata:
    name: postgresdata
    external: true